import "./globals.css";

export const metadata = {
  title: "Pokt Network",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full bg-slate-400">{children}</body>
    </html>
  );
}
